branch-defaults:
  default:
    environment: crypto-bank-client-dev
    group_suffix: null
global:
  application_name: crypto-bank-client
  default_ec2_keyname: crypto-bank-client
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: aws-elasticbeanstalk-ec2-role
  platform_name: Node.js
  platform_version: 18
  profile: eb-cli
  workspace_type: Application
deploy:
  artifact: deploy.zip